### PR TITLE
Improve classify.py

### PR DESCRIPTION
**Pull request by klee2024**
functions up until company_record_linkage() output a dataframe of companies with known classifications. the whole InfoGroup datafile currently has not been read in since I've been testing on 20 chunks. When I attempted to read in the whole file, I got an error on chunk 140 related to the Stock Symbol function w/ requests. I will resolve this for next week. The functions from company_record_linkage() and onwards will be used to classify the companies from the organizations dataframe if there are matches. I'm prioritizing finding the best string similarity metric to match company names for next week. I also forgot to run the pre-linter - sorry!

### CODE REVIEW

**Review by sarahwalker10 — COMMENTED** [review]
Awesome job, Kaya! Good docstrings and well organized code. 
Thank you for adding comments where you are still in progress and have a pseudocode planned. Interested to see how the jacaard similarity analysis turns out. Looking forward to seeing your updates on Friday!

**Comment by klee2024** [comment]
I will need to run the whole InfoGroup dataframe again to account for adding the parent company and ABI column. I was able to get the parent company name based on the parent ABI and have validated this function on the test set, but I would need to apply it to the whole subsetted InfoGroup dataframe. Next steps would be getting the stock symbol of the companies as well as continuing the company matching function to compare the organizations table with the classified company table. 

I'm also not sure why linter is not passing here since the pre-commit was passing locally before pushing.

**Review by sarahwalker10 — COMMENTED** [review]
Great work, Kaya! Thank you for these notes explaining your changes.
Once your work is ready to be integrated into the pipeline, I think we'll move the file imports (i.e. ~ lines 15-63 in src/utils/orgs_classification_data_pipeline.py) into the pipeline script and/or create a config file to pass the file paths as an argument into the pipeline script. For one, this will make your code more generalizable; and two, I know that clinic guidelines for final grading require no hard coding of filepaths. Typically the utils scripts are reserved for functions only. Just something to think about, but no worries for now - excellent work getting the parent companies, industry codes, massive data files, and everything else sorted out for this week!

**Review by trevorspreadbury — CHANGES_REQUESTED** [review]
This looks good and has some well detailed documentation!

Two things to fix before it passes min viable PR:
- add instructions for how to retrieve the datafiles you are using and where we should store them
- make sure the linters pass. We can look into why they aren't on your computer, but you should take the github result as the one to go by in the future

**Comment by klee2024** [comment]
I added instructions for how to retrieve the datafiles and where to store them. I also added packages to requirements.txt that I had used in the orgs_classification_data_pipeline.py pipeline. Please let me know if you're still not able to run it!

**Comment by klee2024** [comment]
I'm working on refactoring the Splink function in linkage in a notebook locally currently with a subset of the InfoGroup data

**Review by sarahwalker10 — COMMENTED** [review]
Thank you for your updates this week, Kaya! And thank you for incorporating the changes from last week. I don't know if I have anything to say for right now since you are still exploring splink on your own. Once you make some discoveries, let me know if you have any questions about incorporating splink into your tasks for improving classification.

**Pull request merged**
